/**
 * Mapping of skill display names to their Simple Icons SVG path data.
 * Uses the `simple-icons` npm package (MIT licensed) for accurate paths.
 * Skills not in this map will render text-only (graceful fallback).
 */
import {
  siReact,
  siTypescript,
  siNextdotjs,
  siRedux,
  siMui,
  siTailwindcss,
  siStyledcomponents,
  siAntdesign,
  siStorybook,
  siExpo,
  siWebpack,
  siNodedotjs,
  siNestjs,
  siExpress,
  siSpringboot,
  siGraphql,
  siDotnet,
  siDocker,
  siKubernetes,
  siGithubactions,
  siGitlab,
  siJenkins,
  siNginx,
  siMongodb,
  siPostgresql,
  siMysql,
  siJest,
  siCypress,
  siCucumber,
  siJunit5,
  siChai,
  siJavascript,
  siPython,
  siOpenjdk,
  siCplusplus,
} from "simple-icons";

export const SKILL_ICONS: Record<string, string> = {
  // Frontend
  React: siReact.path,
  TypeScript: siTypescript.path,
  "Next.js": siNextdotjs.path,
  "Redux Toolkit": siRedux.path,
  MUI: siMui.path,
  "Tailwind CSS": siTailwindcss.path,
  "Styled Components": siStyledcomponents.path,
  "Ant Design": siAntdesign.path,
  Storybook: siStorybook.path,
  "React Native": siReact.path,
  Expo: siExpo.path,
  Webpack: siWebpack.path,
  // Backend
  "Node.js": siNodedotjs.path,
  NestJS: siNestjs.path,
  "Express.js": siExpress.path,
  "Spring Boot": siSpringboot.path,
  GraphQL: siGraphql.path,
  ".NET Core": siDotnet.path,
  // DevOps & Cloud
  Docker: siDocker.path,
  Kubernetes: siKubernetes.path,
  "GitHub Actions": siGithubactions.path,
  "GitLab CI": siGitlab.path,
  Jenkins: siJenkins.path,
  NGINX: siNginx.path,
  // Databases
  MongoDB: siMongodb.path,
  PostgreSQL: siPostgresql.path,
  MySQL: siMysql.path,
  // Testing
  Jest: siJest.path,
  Cypress: siCypress.path,
  Cucumber: siCucumber.path,
  JUnit: siJunit5.path,
  Chai: siChai.path,
  // Languages
  JavaScript: siJavascript.path,
  Python: siPython.path,
  Java: siOpenjdk.path,
  "C++": siCplusplus.path,
};
